repos:
  -   repo: local
      hooks:
      -   id: meta-lint-commit
          name: Lint commit messages
          entry: ./scripts/lint-commit.sh
          language: script
          stages: [commit-msg]
  -   repo: https://github.com/pycqa/flake8
      rev: 7.0.0
      hooks:
        -   id: flake8
  -   repo: https://github.com/psf/black
      rev: 23.12.1
      hooks:
        - id: black
          language_version: python3.11
  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v3.12.0
      hooks:
        -   id: reorder-python-imports
            args: [--py3-plus]
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.8.0
      hooks:
      -   id: mypy
          additional_dependencies: []
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-case-conflict